version: '3'

volumes:
  data:
  postgres:
    driver: local

services:
  api:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8085:80"
    volumes:
        - ./data:/data
    environment:
        - POSTGRES_DATABASE=api
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    restart: always

  db:
    image: postgres:alpine
    container_name: api-db
    restart: unless-stopped
    hostname: postgres
    ports:
      - "19200:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    volumes:
      - postgres:/var/lib/postgresql/data