version: '3'

volumes:
  data:
  mysql:
    driver: local

services:
  api:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8085:80"
    depends_on:
      - mysql
    volumes:
        - ./:/var/www/html # Mount the current directory to /var/www/html for dev purposes
#        - data:data # Mount the data volume to /var/www/html/data for prod purposes
    env_file:
      - ./.env
    restart: always


  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest-aarch64
    ports:
        - "3307:3306"
    volumes:
        - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "api"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    tty: true
    stdin_open: true


  phpmyadmin:
    container_name: phpmyadmin
    image: arm64v8/phpmyadmin
    ports:
        - "2083:80"
    restart: always
    environment:
        PMA_HOST: mysql
    depends_on:
        - mysql